# fly.toml app configuration file generated for webtweets-dawn-forest-2637 on 2024-06-26T09:10:17+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'webtweets-dawn-forest-2637'
primary_region = 'jnb'

[build]

[env]
  MONGO_URI = 'mongodb+srv://myAtlasDBUser:Enockay23@bmgpfws.bfx6ekr.mongodb.net/Webtweets?retryWrites=true&w=majority'
  PORT = '3000'
  TIKTOK_CLIENT_ID = 'awh3y2l4qe3z5a5c'
  TIKTOK_CLIENT_SECRET = 'kvJPSiXqfhdeQnPHX15g34OKRyflYXUe'
  INSTAGRAM_CLIENT_ID = '840372054180788'
  INSTAGRAM_CLIENT_SECRET = '237a1db43e61d455d6d313fdef332542'
  INSTAGRAM_CALLBACK_URL = 'http://yourdomain.com/auth/instagram/callback'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
